{% set version = "2.0.4" %}

package:
  name: bob.db.wine
  version: {{ version }}

source:
  fn: bob.db.wine-{{ version }}.zip
  md5: bb12c4c6ef29f81e34a42d2682152346
  url: https://pypi.io/packages/source/b/bob.db.wine/bob.db.wine-{{ version }}.zip

build:
  number: 0
  skip: true  # [win]
  script: python -B setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - bob.db.base

  run:
    - python
    - bob.db.base

test:
  commands:
    - nosetests -sv bob.db.wine

  imports:
    - bob
    - bob.db
    - bob.db.wine

  requires:
    - nose

about:
  home: https://pypi.python.org/pypi/bob.db.wine
  license: GNU General Public License v3 (GPLv3)
  summary: Wine Database for bob

extra:
  recipe-maintainers:
    - 183amir
